version: 2.1

orbs:
  maven: circleci/maven@1.2.0
  codecov: codecov/codecov@3.1.0

executors:
  jdk11:
    docker:
      - image: cimg/openjdk:11.0.12
    working_directory: /tmp

jobs:
  upload-to-codecov:
    executor: jdk11
    steps:
      - codecov/upload:
          file: target/jacoco.exec

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk11
          pre-steps:
            - run: mkdir -p workspace
          post-steps:
            - put_code_coverage_in_workspace:
                - run: cp target/jacoco.exec workspace/jacoco.exec
            - persist_to_workspace:
                root: workspace
                paths:
                  - jacoco.exec
      - upload-to-codecov:
          requires:
            - maven/test
