version: 2.1

orbs:
  maven: circleci/maven@1.2.0
  codecov: codecov/codecov@3.1.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - maven/test
      - codecov/upload
