version: 2
jobs:
    build:
        docker:
          - image: cimg/openjdk:11.0.12
        steps:
        - checkout
        - run: mvn test
        - store_test_results:
            path: target/surefire-reports
        - run:
            name: Send to CodeCov
            command: bash <(curl -s https://codecov.io/bash)
