CREATE TABLE USER
(
    ID        UUID PRIMARY KEY,
    VERSION   INTEGER,
    USERNAME  VARCHAR(255),
    PASSWORD  VARCHAR(255),
    LAST_NAME VARCHAR(255)
);
CREATE TABLE OWNER
(
    ID         UUID PRIMARY KEY,
    USER       UUID,
    VERSION    INTEGER,
    FIRST_NAME VARCHAR(255),
    LAST_NAME  VARCHAR(255),
    FOREIGN KEY (USER) REFERENCES USER (ID)
);
