CREATE TABLE IF NOT EXISTS USER
(
    ID        UUID PRIMARY KEY,
    VERSION   INTEGER,
    USERNAME  VARCHAR(255),
    PASSWORD  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PERSONAL_DATA
(
    ID UUID PRIMARY KEY,
    VERSION INTEGER,
    USER UUID,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    FOREIGN KEY (USER) REFERENCES USER (ID)
)
;
CREATE TABLE IF NOT EXISTS OWNER
(
    ID         UUID PRIMARY KEY,
    PERSONAL_DATA UUID,
    VERSION    INTEGER,
    FOREIGN KEY (PERSONAL_DATA) REFERENCES PERSONAL_DATA (ID)
);

CREATE TABLE IF NOT EXISTS VET
(
    ID         UUID PRIMARY KEY,
    USER       UUID,
    PERSONAL_DATA UUID,
    VERSION    INTEGER,
    FOREIGN KEY (PERSONAL_DATA) REFERENCES PERSONAL_DATA (ID)
);
